### ISSUE TITLE
Define protocol using protobuf?

### ISSUE THREAD

**Issue by Andrey9kin** [Ericsson/eiffel-remrem-semantics#20]
Hi!

Have you considered using protobuf to define the protocol? I remember @d-stahl-ericsson mentioning that it was considered during initial implementation but then wasn't chosen due to the reason that I don't remember. @d-stahl-ericsson what was it?

I believe we can gain a lot from using protobuf and generating protocol definitions instead of coding classes manually

Here are few examples
https://github.com/Praqma/tracey-protocol-eiffel/blob/master/src/main/proto/eiffel_event.proto
https://github.com/Praqma/tracey-protocol-eiffel/blob/master/src/main/proto/eiffel_source_change_created_event.proto

Moreover, we will get few problems out of the list - serialization, deserialization, protocol extensions and versioning.

BR, Andrey

**Comment by d-stahl-ericsson** [comment]
As for protobuf, it's not so much that we decided against it. Rather we didn't decide for it. Whether it would be conducive to use inside of Remrem is something I'm not qualified to answer, as I haven't participated in Remrem at that level of detail. Pinging @danielyinanc :)
